project:
  type: website
  output-dir: docs

editor:
  render-on-save: true

website:
  title: "myblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        text: Github
        href: https://github.com/Harrisonlee0530
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/harrison-l-b7253a23a

format:
  html:
    theme:
      light: flatly
      dark: darkly
      # - cosmo
      # - brand
    css: styles.css
    toc: true

